In [1]:
import tensorflow as tf
print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))


Num GPUs Available: 0


In [2]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt

In [3]:
training_set = tf.keras.utils.image_dataset_from_directory(
    'train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

print("Danish")

Found 70295 files belonging to 38 classes.
Danish


In [4]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

print("Danish")

Found 17572 files belonging to 38 classes.
Danish


In [5]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [6]:
validation_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [7]:
for x,y in training_set:
    print(x, x.shape)
    print(y, y.shape)
    break

tf.Tensor(
[[[[139.   140.   135.  ]
   [139.   140.   135.  ]
   [138.5  139.5  134.5 ]
   ...
   [134.5  138.5  137.5 ]
   [135.   139.   138.  ]
   [137.   141.   140.  ]]

  [[138.5  139.5  134.5 ]
   [139.   140.   135.  ]
   [139.   140.   135.  ]
   ...
   [131.5  135.5  134.5 ]
   [132.25 136.25 135.25]
   [133.5  137.5  136.5 ]]

  [[136.   137.   132.  ]
   [137.   138.   133.  ]
   [138.25 139.25 134.25]
   ...
   [130.5  134.5  133.5 ]
   [130.25 134.25 133.25]
   [131.   135.   134.  ]]

  ...

  [[ 91.5   86.5   80.5 ]
   [ 91.25  86.25  80.25]
   [ 91.    86.    80.  ]
   ...
   [ 62.75  57.75  51.75]
   [ 64.    59.    53.  ]
   [ 64.    59.    53.  ]]

  [[ 90.75  85.75  79.75]
   [ 90.    85.    79.  ]
   [ 88.75  83.75  77.75]
   ...
   [ 64.25  59.25  53.25]
   [ 64.5   59.5   53.5 ]
   [ 68.    63.    57.  ]]

  [[ 91.25  86.25  80.25]
   [ 90.    85.    79.  ]
   [ 88.25  83.25  77.25]
   ...
   [ 64.    59.    53.  ]
   [ 61.25  56.25  50.25]
   [ 65.5   60.5   5

In [8]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPool2D, Flatten, Dense, Dropout, Input


In [9]:
model = Sequential()

In [10]:
#building model

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

model = Sequential()

model.add(Input(shape=(128, 128, 3)))  # Explicit Input layer

model.add(Conv2D(filters=32, kernel_size=3, padding='same', activation='relu'))
model.add(Conv2D(filters=32, kernel_size=3, padding='same', activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))

model.add(Conv2D(filters=64, kernel_size=3, padding='same', activation='relu'))
model.add(Conv2D(filters=64, kernel_size=3, padding='same', activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))

model.add(Conv2D(filters=128, kernel_size=3, padding='same', activation='relu'))
model.add(Conv2D(filters=128, kernel_size=3, padding='same', activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))

model.add(Conv2D(filters=256, kernel_size=3, padding='same', activation='relu'))
model.add(Conv2D(filters=256, kernel_size=3, padding='same', activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))

model.add(Conv2D(filters=512, kernel_size=3, padding='same', activation='relu'))
model.add(Conv2D(filters=512, kernel_size=3, padding='same', activation='relu'))
model.add(MaxPool2D(pool_size=2, strides=2))

model.add(Dropout(0.25))  # To avoid overfitting

model.add(Flatten())

model.add(Dense(units=1500, activation='relu'))
model.add(Dropout(0.4))

# Output Layer
model.add(Dense(units=38, activation='softmax'))


print("Danish")


Danish


In [11]:
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001), loss='categorical_crossentropy', metrics=['accuracy'])

print("danish")

danish


In [12]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 128, 128, 32)        │             896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 128, 128, 32)        │           9,248 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 64, 64, 32)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_2 (Conv2D)                    │ (None, 64, 64, 64)          │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_3 (Conv2D)                    │ (None, 64, 64, 64)          │          36,928 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 32, 32, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_4 (Conv2D)                    │ (None, 32, 32, 128)         │          73,856 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_5 (Conv2D)                    │ (None, 32, 32, 128)         │         147,584 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_2 (MaxPooling2D)       │ (None, 16, 16, 128)         │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_6 (Conv2D)                    │ (None, 16, 16, 256)         │         295,168 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_7 (Conv2D)                    │ (None, 16, 16, 256)         │         590,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_3 (MaxPooling2D)       │ (None, 8, 8, 256)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_8 (Conv2D)                    │ (None, 8, 8, 512)           │       1,180,160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_9 (Conv2D)                    │ (None, 8, 8, 512)           │       2,359,808 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_4 (MaxPooling2D)       │ (None, 4, 4, 512)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 4, 4, 512)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 8192)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1500)                │      12,289,500 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 1500)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 38)                  │          57,038 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 17,058,762 (65.07 MB)

 Trainable params: 17,058,762 (65.07 MB)

 Non-trainable params: 0 (0.00 B)

In [13]:
training_history = model.fit(x=training_set, validation_data=validation_set, epochs=10)

Epoch 1/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2362s 1s/step - accuracy: 0.4847 - loss: 1.8240 - val_accuracy: 0.8903 - val_loss: 0.3419
Epoch 2/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2302s 1s/step - accuracy: 0.8794 - loss: 0.3765 - val_accuracy: 0.9295 - val_loss: 0.2138
Epoch 3/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2299s 1s/step - accuracy: 0.9289 - loss: 0.2249 - val_accuracy: 0.9456 - val_loss: 0.1663
Epoch 4/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2285s 1s/step - accuracy: 0.9477 - loss: 0.1533 - val_accuracy: 0.9509 - val_loss: 0.1500
Epoch 5/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2283s 1s/step - accuracy: 0.9634 - loss: 0.1103 - val_accuracy: 0.9497 - val_loss: 0.1593
Epoch 6/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2263s 1s/step - accuracy: 0.9712 - loss: 0.0870 - val_accuracy: 0.9651 - val_loss: 0.1081
Epoch 7/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2312s 1s/step - accuracy: 0.9770 - loss: 0.0727 - val_accuracy: 0.9626 - val_loss: 0.1230
Epoch 8/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 2296s 1s/step - accuracy: 0.9798 -

In [19]:
train_loss, train_acc = model.evalute(training_set)

AttributeError: 'Sequential' object has no attribute 'evalute'

In [15]:
print(train_loss, train_acc)

NameError: name 'train_loss' is not defined

In [ ]:
val_loss, val_acc = model.evelute(validation_set)

In [ ]:
print(val_loss, val_acc)

In [20]:
model.save("trained_model.pkl")

ValueError: Invalid filepath extension for saving. Please add either a `.keras` extension for the native Keras format (recommended) or a `.h5` extension. Use `model.export(filepath)` if you want to export a SavedModel for use with TFLite/TFServing/etc. Received: filepath=trained_model.pkl.

In [1]:
training_history.history

NameError: name 'training_history' is not defined

In [6]:
test_set = tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=False,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False
)

Found 17572 files belonging to 38 classes.


In [14]:
y_pred = model.predict(test_set)
y_pred, y_pred.shape

550/550 ━━━━━━━━━━━━━━━━━━━━ 126s 228ms/step


(array([[0.00292488, 0.01758122, 0.02137333, ..., 0.04214168, 0.00727351,
         0.01002576],
        [0.00392169, 0.01551384, 0.01390275, ..., 0.05733444, 0.00974528,
         0.00850321],
        [0.00442055, 0.00664346, 0.00951925, ..., 0.03962552, 0.00472137,
         0.0102554 ],
        ...,
        [0.00620058, 0.01846622, 0.01431135, ..., 0.03655932, 0.00939099,
         0.01133568],
        [0.00581018, 0.01826757, 0.01507002, ..., 0.03795733, 0.00894954,
         0.01334631],
        [0.00265916, 0.02241061, 0.01570725, ..., 0.04697758, 0.00842717,
         0.00977902]], dtype=float32),
 (17572, 38))

In [16]:
predicted_categories = tf.argmax(y_pred, axis=1)

In [17]:
predicted_categories

<tf.Tensor: shape=(17572,), dtype=int64, numpy=array([27, 17, 17, ..., 18, 17, 18])>

In [18]:
true_categories = tf.concat([y for x,y in test_set], axis=0) 

In [19]:
true_categories

<tf.Tensor: shape=(17572, 38), dtype=float32, numpy=
array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)>

In [21]:
y_true = tf.argmax(true_categories, axis=1)
y_true

<tf.Tensor: shape=(17572,), dtype=int64, numpy=array([ 0,  0,  0, ..., 37, 37, 37])>

In [22]:
from sklearn.metrics import classification_report

In [27]:
class_name = validation_set.class_names

In [28]:
print(classification_report(y_true,predicted_categories,target_name=class_name))

TypeError: got an unexpected keyword argument 'target_name'